import { BarChart3, Download, Clock, Mail, FileText, Shield, Users, Activity } from 'lucide-react'

const reports = [
  { id: 'r1', name: 'Security Summary', description: 'Weekly summary of violations, incidents, and enforcement actions.', icon: Shield, color: 'bg-red-500', lastRun: '2026-07-12', schedule: 'Weekly' },
  { id: 'r2', name: 'User Activity Report', description: 'Per-user AI usage, top prompts, risk scores, and behavioral trends.', icon: Users, color: 'bg-blue-500', lastRun: '2026-07-13', schedule: 'Daily' },
  { id: 'r3', name: 'Compliance Report', description: 'GDPR, HIPAA, SOX compliance posture and data handling summary.', icon: FileText, color: 'bg-green-500', lastRun: '2026-07-01', schedule: 'Monthly' },
  { id: 'r4', name: 'AI Usage Analytics', description: 'Tool adoption, usage trends, token consumption, and cost analysis.', icon: Activity, color: 'bg-purple-500', lastRun: '2026-07-13', schedule: 'Daily' },
  { id: 'r5', name: 'Incident Report', description: 'All incidents by severity, category, department, and resolution time.', icon: BarChart3, color: 'bg-orange-500', lastRun: '2026-07-12', schedule: 'Weekly' },
  { id: 'r6', name: 'Policy Effectiveness', description: 'Policy hit rates, false positives, and enforcement outcome analysis.', icon: Shield, color: 'bg-slate-600', lastRun: '2026-07-07', schedule: 'Weekly' },
]

export default function Reports() {
  return (
    <div className="p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Reports</h1>
          <p className="text-sm text-gray-500">Generate, schedule, and export security reports</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {reports.map(report => (
          <div key={report.id} className="bg-white rounded-xl border border-gray-200 p-5 hover:shadow-md transition-shadow">
            <div className="flex items-start gap-3 mb-3">
              <div className={`w-10 h-10 rounded-xl ${report.color} flex items-center justify-center flex-shrink-0`}>
                <report.icon className="w-5 h-5 text-white" />
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 text-sm">{report.name}</h3>
                <p className="text-xs text-gray-500 mt-0.5">{report.description}</p>
              </div>
            </div>

            <div className="flex items-center gap-4 text-xs text-gray-400 mb-4">
              <div className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                <span>Last run: {report.lastRun}</span>
              </div>
              <div className="flex items-center gap-1">
                <Activity className="w-3 h-3" />
                <span>{report.schedule}</span>
              </div>
            </div>

            <div className="flex gap-2">
              <button className="flex-1 flex items-center justify-center gap-1.5 py-2 bg-blue-600 text-white text-xs rounded-lg font-medium hover:bg-blue-700 transition-colors">
                <BarChart3 className="w-3.5 h-3.5" />
                Generate
              </button>
              <button className="p-2 border border-gray-200 rounded-lg text-gray-500 hover:bg-gray-50 hover:text-gray-700">
                <Download className="w-4 h-4" />
              </button>
              <button className="p-2 border border-gray-200 rounded-lg text-gray-500 hover:bg-gray-50 hover:text-gray-700">
                <Mail className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Recent exports */}
      <div className="mt-8">
        <h2 className="text-sm font-semibold text-gray-700 mb-3">Recent Exports</h2>
        <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="text-left px-4 py-2.5 text-xs text-gray-500 font-medium">Report</th>
                <th className="text-left px-4 py-2.5 text-xs text-gray-500 font-medium hidden md:table-cell">Generated</th>
                <th className="text-left px-4 py-2.5 text-xs text-gray-500 font-medium hidden md:table-cell">Format</th>
                <th className="text-left px-4 py-2.5 text-xs text-gray-500 font-medium hidden md:table-cell">Generated by</th>
                <th className="px-4 py-2.5" />
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {[
                { name: 'Security Summary — Week 27', date: '2026-07-12 09:00', format: 'PDF', by: 'Scheduled' },
                { name: 'User Activity Report — Jul 13', date: '2026-07-13 08:00', format: 'CSV', by: 'Scheduled' },
                { name: 'Compliance Report — June 2026', date: '2026-07-01 07:00', format: 'PDF', by: 'Arun Kumar' },
                { name: 'Incident Report — Week 26', date: '2026-07-05 09:00', format: 'XLSX', by: 'Scheduled' },
              ].map((row, i) => (
                <tr key={i} className="hover:bg-gray-50">
                  <td className="px-4 py-3 text-xs font-medium text-gray-800">{row.name}</td>
                  <td className="px-4 py-3 text-xs text-gray-500 hidden md:table-cell">{row.date}</td>
                  <td className="px-4 py-3 hidden md:table-cell">
                    <span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded">{row.format}</span>
                  </td>
                  <td className="px-4 py-3 text-xs text-gray-500 hidden md:table-cell">{row.by}</td>
                  <td className="px-4 py-3 text-right">
                    <button className="text-xs text-blue-600 hover:underline flex items-center gap-1 ml-auto">
                      <Download className="w-3 h-3" />
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
